# Generated by Django 4.2.1 on 2024-06-12 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_patient2_password_alter_bill2_billdate_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="appointment2",
            table="Appointment2",
        ),
    ]
